# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      enabled: true
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+IgnoreUnrecognizedVMOptions
      TERM: dumb
    
    steps:
      - checkout

#      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "build.gradle" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

      - run: chmod +x gradlew

      - run: ./gradlew --version

      - run: ./gradlew dependencies
#
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run:
          name: Run tests
          command: ./gradlew test jacocoTestReport --no-daemon
          no_output_timeout: 60m

      - run:
          name: Coveralls
          command: ./gradlew coveralls

