# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      enabled: true

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+IgnoreUnrecognizedVMOptions
      TERM: dumb

    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew --version
      - run: ./gradlew dependencies
      - run:
          name: Run tests and execute the scanner
          command: ./gradlew sonarqube -Dsonar.projectKey=danielsun1106_groovy-parser -Dsonar.organization=danielsun1106 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
          no_output_timeout: 60m
