# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      enabled: true

    working_directory: ~/repo

    environment:
      TERM: dumb
      ASYNC_PROFILER_HOME: /tmp/async-profiler

    steps:
      - checkout
      - run: wget https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.6/async-profiler-1.6-linux-x64.tar.gz
      - run: mkdir $ASYNC_PROFILER_HOME && tar xvfz async-profiler-1.6-linux-x64.tar.gz -C $ASYNC_PROFILER_HOME
      - run: chmod -R 755 $ASYNC_PROFILER_HOME
      - run: chmod +x gradlew
      - run: ./gradlew --version
      - run: ./gradlew dependencies
      - run: mkdir -p build/reports
      - run:
          name: Run tests and Execute the scanner
          command: sudo ./gradlew test
          no_output_timeout: 60m
      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: build/test-results/test
      - store_artifacts:
          # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: build/reports
          when: always
